#!/bin/bash

# Usage ./multirun small.vtu 5

# Queue number of jobs specified in $2
for ((i=0;i<$2;i++))
do
  if [ -n "$jobids" ]
    then
    # Separate job ids with : for -W argument of final job
    jobids=$jobids":"
  fi
  echo "Queueing job $i"
  jobids=$jobids`echo "${HOME}/smooth/job $1" | qsub -N test -o ${HOME}/smooth/out -e ${HOME}/smooth/err`
done

echo "Queueing jobs-done"

# Queue a job which depends upon the completion of all jobs started by this script
echo "${HOME}/smooth/jobs-done $jobids" | qsub -N "jobs-done" -W depend=afterok:$jobids > /dev/null
echo "Jobs queued."
